scripts:
      - name: Get Flutter Packages
        script: |
          # Clean the workspace first to wipe out the old 13.0 cache
          flutter clean
          flutter pub get
          
      - name: Regenerate iOS Config for SPM
        script: |
          # This is the magic command! It forces Flutter to update SPM to 15.0
          flutter build ios --config-only
          
      - name: Build Flutter iOS App
        script: |
          flutter build ios --release --no-codesign
          
      - name: Package Unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r Hawalik.ipa Payload/