// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9sUSCPQ94hCpnOg0rq5qy3mS9NNHD19U',
    appId: '1:1094068266777:web:33ca4ad60cb584cabd0788',
    messagingSenderId: '1094068266777',
    projectId: 'hawalik-42c79',
    authDomain: 'hawalik-42c79.firebaseapp.com',
    storageBucket: 'hawalik-42c79.firebasestorage.app',
    measurementId: 'G-3X1M3ZEC0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDq7lw09h7e791sB7CiICr61cMiPHWwa8',
    appId: '1:1094068266777:android:e9a0356b452329c1bd0788',
    messagingSenderId: '1094068266777',
    projectId: 'hawalik-42c79',
    storageBucket: 'hawalik-42c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzE6DqqYUbpW1z1bbqzINsPwTW2Wbqwc',
    appId: '1:1094068266777:ios:43d2b0e736422e5ebd0788',
    messagingSenderId: '1094068266777',
    projectId: 'hawalik-42c79',
    storageBucket: 'hawalik-42c79.firebasestorage.app',
    iosBundleId: 'com.example.hawalik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPzE6DqqYUbpW1z1bbqzINsPwTW2Wbqwc',
    appId: '1:1094068266777:ios:43d2b0e736422e5ebd0788',
    messagingSenderId: '1094068266777',
    projectId: 'hawalik-42c79',
    storageBucket: 'hawalik-42c79.firebasestorage.app',
    iosBundleId: 'com.example.hawalik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9sUSCPQ94hCpnOg0rq5qy3mS9NNHD19U',
    appId: '1:1094068266777:web:431ab5ed83661dc2bd0788',
    messagingSenderId: '1094068266777',
    projectId: 'hawalik-42c79',
    authDomain: 'hawalik-42c79.firebaseapp.com',
    storageBucket: 'hawalik-42c79.firebasestorage.app',
    measurementId: 'G-7MDP59BTKH',
  );
}
